# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/type/v3/semantic_version.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
from udpa.annotations import versioning_pb2 as udpa_dot_annotations_dot_versioning__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$envoy/type/v3/semantic_version.proto\x12\renvoy.type.v3\x1a\x1dudpa/annotations/status.proto\x1a!udpa/annotations/versioning.proto\"\x90\x01\n\x0fSemanticVersion\x12!\n\x0cmajor_number\x18\x01 \x01(\rR\x0bmajorNumber\x12!\n\x0cminor_number\x18\x02 \x01(\rR\x0bminorNumber\x12\x14\n\x05patch\x18\x03 \x01(\rR\x05patch:!\x9a\xc5\x88\x1e\x1c\n\x1a\x65nvoy.type.SemanticVersionB\xc4\x01\n\x11\x63om.envoy.type.v3B\x14SemanticVersionProtoP\x01Z;github.com/envoyproxy/go-control-plane/envoy/type/v3;typev3\xa2\x02\x03\x45TX\xaa\x02\rEnvoy.Type.V3\xca\x02\rEnvoy\\Type\\V3\xe2\x02\x19\x45nvoy\\Type\\V3\\GPBMetadata\xea\x02\x0f\x45nvoy::Type::V3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envoy.type.v3.semantic_version_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.envoy.type.v3B\024SemanticVersionProtoP\001Z;github.com/envoyproxy/go-control-plane/envoy/type/v3;typev3\242\002\003ETX\252\002\rEnvoy.Type.V3\312\002\rEnvoy\\Type\\V3\342\002\031Envoy\\Type\\V3\\GPBMetadata\352\002\017Envoy::Type::V3\272\200\310\321\006\002\020\002'
  _globals['_SEMANTICVERSION']._loaded_options = None
  _globals['_SEMANTICVERSION']._serialized_options = b'\232\305\210\036\034\n\032envoy.type.SemanticVersion'
  _globals['_SEMANTICVERSION']._serialized_start=122
  _globals['_SEMANTICVERSION']._serialized_end=266
# @@protoc_insertion_point(module_scope)
