# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/core/v3/extension.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$envoy/config/core/v3/extension.proto\x12\x14\x65nvoy.config.core.v3\x1a\x19google/protobuf/any.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"v\n\x14TypedExtensionConfig\x12\x1b\n\x04name\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x04name\x12\x41\n\x0ctyped_config\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyB\x08\xfa\x42\x05\xa2\x01\x02\x08\x01R\x0btypedConfigB\xe9\x01\n\x18\x63om.envoy.config.core.v3B\x0e\x45xtensionProtoP\x01ZBgithub.com/envoyproxy/go-control-plane/envoy/config/core/v3;corev3\xa2\x02\x03\x45\x43\x43\xaa\x02\x14\x45nvoy.Config.Core.V3\xca\x02\x14\x45nvoy\\Config\\Core\\V3\xe2\x02 Envoy\\Config\\Core\\V3\\GPBMetadata\xea\x02\x17\x45nvoy::Config::Core::V3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envoy.config.core.v3.extension_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.envoy.config.core.v3B\016ExtensionProtoP\001ZBgithub.com/envoyproxy/go-control-plane/envoy/config/core/v3;corev3\242\002\003ECC\252\002\024Envoy.Config.Core.V3\312\002\024Envoy\\Config\\Core\\V3\342\002 Envoy\\Config\\Core\\V3\\GPBMetadata\352\002\027Envoy::Config::Core::V3\272\200\310\321\006\002\020\002'
  _globals['_TYPEDEXTENSIONCONFIG'].fields_by_name['name']._loaded_options = None
  _globals['_TYPEDEXTENSIONCONFIG'].fields_by_name['name']._serialized_options = b'\372B\004r\002\020\001'
  _globals['_TYPEDEXTENSIONCONFIG'].fields_by_name['typed_config']._loaded_options = None
  _globals['_TYPEDEXTENSIONCONFIG'].fields_by_name['typed_config']._serialized_options = b'\372B\005\242\001\002\010\001'
  _globals['_TYPEDEXTENSIONCONFIG']._serialized_start=145
  _globals['_TYPEDEXTENSIONCONFIG']._serialized_end=263
# @@protoc_insertion_point(module_scope)
