# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/annotations/deprecation.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#envoy/annotations/deprecation.proto\x12\x11\x65nvoy.annotations\x1a google/protobuf/descriptor.proto:T\n\x15\x64isallowed_by_default\x12\x1d.google.protobuf.FieldOptions\x18\xe7\xad\xaeZ \x01(\x08R\x13\x64isallowedByDefault:_\n\x1b\x64\x65precated_at_minor_version\x12\x1d.google.protobuf.FieldOptions\x18\xf2\xe8\x80K \x01(\tR\x18\x64\x65precatedAtMinorVersion:a\n\x1a\x64isallowed_by_default_enum\x12!.google.protobuf.EnumValueOptions\x18\xf5\xce\xb6! \x01(\x08R\x17\x64isallowedByDefaultEnum:l\n deprecated_at_minor_version_enum\x12!.google.protobuf.EnumValueOptions\x18\xc1\xbe\xb3V \x01(\tR\x1c\x64\x65precatedAtMinorVersionEnumB\xc8\x01\n\x15\x63om.envoy.annotationsB\x10\x44\x65precationProtoP\x01Z8github.com/envoyproxy/go-control-plane/envoy/annotations\xa2\x02\x03\x45\x41X\xaa\x02\x11\x45nvoy.Annotations\xca\x02\x11\x45nvoy\\Annotations\xe2\x02\x1d\x45nvoy\\Annotations\\GPBMetadata\xea\x02\x12\x45nvoy::Annotationsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envoy.annotations.deprecation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.envoy.annotationsB\020DeprecationProtoP\001Z8github.com/envoyproxy/go-control-plane/envoy/annotations\242\002\003EAX\252\002\021Envoy.Annotations\312\002\021Envoy\\Annotations\342\002\035Envoy\\Annotations\\GPBMetadata\352\002\022Envoy::Annotations'
# @@protoc_insertion_point(module_scope)
